### ISSUE TITLE
Help needed: Tcp server startup function breaks app

### ISSUE THREAD

**Issue by Toshiba01** [daniel-krich/TCP-Server-Framework#1]
Hi, 

Probably this isn't a problem with your code, but I'm struggling:

I have another app written and I wanted to attach this framework to it. I have added the files to my project and done the right linking, everything compiles and no errors - even the Server works but unfortunately the main window doesn't get initialised anymore. 

The app doesn't crash as is still running in taskManager, as said the server accepts connections, but all the other functions and functionalities are broken. 

My app doesn't have a "main" function for startup, instead uses InitApp, where I call:
 `dk::TCPServer* server new dk::TCPServer(port); ` --> here is where all breaks, as it doesn't load up the code after this point.

Unfortunately can't share much of a code as it's part of my employer's and we're not allowed to share it. Any input would be appreciated.

**Comment by daniel-krich** [comment]
Hey,

Sorry for the late reply, but you probably would want to create a seperate thread and run the server on it, simply because the server will block the main/UI thread that its running on.

**Comment by daniel-krich** [comment]
Hey,

Sorry for the late reply, but you probably would want to create a seperate thread and run the server on it, simply because the server will block the main/UI thread that its running on.

**Comment by Toshiba01** [comment]
Hi Daniel, 

Thank you for your input. I'm a beginner in C++, so still learning the iNs and OUTs of it! 
I appreciate it, 

Regards, 
Ioan
